# Generated by Django 3.1.3 on 2020-12-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreectname', models.CharField(blank=True, max_length=250, null=True)),
                ('coreectlastname', models.CharField(blank=True, max_length=250, null=True)),
                ('coreectmovie', models.CharField(blank=True, max_length=250, null=True)),
                ('coreectcity', models.CharField(blank=True, max_length=250, null=True)),
                ('coreectage', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('lastname', models.CharField(blank=True, max_length=250, null=True)),
                ('movie', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
